/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app02;

import app02.Clases.CuentaAhorro;
import app02.Clases.TarjetaCredito;
import app02.Clases.TarjetaDebito;
import javax.swing.JOptionPane;

/**
 *
 * @author icol2
 */
public class AppFrame extends javax.swing.JFrame {

    TarjetaCredito tarjetaCredito = new TarjetaCredito(0);
    CuentaAhorro cuentaAhorro = new CuentaAhorro(0);
    TarjetaDebito tarjectaDebito = new TarjetaDebito(0);

    /**
     * Creates new form AppMain
     */
    public AppFrame() {
        initComponents();
        refrescarMontoCuentaAhorro();
        refrescarMontoCuentaDebito();
        refrescarMontoCredito();
    }

    private void refrescarMontoCuentaAhorro() {
        this.txtMontoActualCuentaAhorro.setText(this.cuentaAhorro.getMontoActual() + "");
    }

    private void refrescarMontoCuentaDebito() {
        this.txtMontoActualDebito.setText(this.tarjectaDebito.getMontoActual() + "");
    }

    private void refrescarMontoCredito() {
        this.txtMontoActualCredito.setText(this.tarjetaCredito.getMontoActual() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnVerMontoTarjetaDebito = new javax.swing.JButton();
        txtMontoActualDebito = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDepositoDebito = new javax.swing.JTextField();
        btnDepositarDebito = new javax.swing.JButton();
        btnRetirarDebito = new javax.swing.JButton();
        txtRetirarDebito = new javax.swing.JTextField();
        lblAccion3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnVerMontoTarjetaCredito = new javax.swing.JButton();
        txtMontoActualCredito = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDepositoCredito = new javax.swing.JTextField();
        btnDepositarCredito = new javax.swing.JButton();
        btnSumaIntereses = new javax.swing.JButton();
        txtSumaInteresesCredito = new javax.swing.JTextField();
        lblAccion2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnVerMontoCuentaAhorro = new javax.swing.JButton();
        btnDepositarCuentaAhorro = new javax.swing.JButton();
        btnInvertir = new javax.swing.JButton();
        txtMontoActualCuentaAhorro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblAccion1 = new javax.swing.JLabel();
        txtInvertirAhorro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDepositoAhorro = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Banco MexBank");

        btnVerMontoTarjetaDebito.setText("Ver Monto Actual");
        btnVerMontoTarjetaDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMontoTarjetaDebitoActionPerformed(evt);
            }
        });

        txtMontoActualDebito.setEnabled(false);

        jLabel9.setText("Monto Actual");

        jLabel10.setText("Depositar");

        btnDepositarDebito.setText("Depositar");
        btnDepositarDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarDebitoActionPerformed(evt);
            }
        });

        btnRetirarDebito.setText("Aceptar");
        btnRetirarDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarDebitoActionPerformed(evt);
            }
        });

        lblAccion3.setText("Retirar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(lblAccion3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRetirarDebito)
                    .addComponent(txtMontoActualDebito, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txtDepositoDebito))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDepositarDebito)
                    .addComponent(btnVerMontoTarjetaDebito)
                    .addComponent(btnRetirarDebito))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMontoActualDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVerMontoTarjetaDebito))
                    .addComponent(jLabel9))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDepositoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepositarDebito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRetirarDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccion3)
                    .addComponent(btnRetirarDebito))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tarjeta de debito", jPanel1);

        btnVerMontoTarjetaCredito.setText("Ver Monto Actual");
        btnVerMontoTarjetaCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMontoTarjetaCreditoActionPerformed(evt);
            }
        });

        txtMontoActualCredito.setEnabled(false);

        jLabel7.setText("Monto Actual");

        jLabel8.setText("Depositar");

        btnDepositarCredito.setText("Depositar");
        btnDepositarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarCreditoActionPerformed(evt);
            }
        });

        btnSumaIntereses.setText("Aceptar");
        btnSumaIntereses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaInteresesActionPerformed(evt);
            }
        });

        lblAccion2.setText("Suma Intereses");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(lblAccion2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSumaInteresesCredito)
                    .addComponent(txtMontoActualCredito, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txtDepositoCredito))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDepositarCredito)
                    .addComponent(btnVerMontoTarjetaCredito)
                    .addComponent(btnSumaIntereses))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMontoActualCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVerMontoTarjetaCredito))
                    .addComponent(jLabel7))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDepositoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepositarCredito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSumaInteresesCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccion2)
                    .addComponent(btnSumaIntereses))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tarjeta de Credito", jPanel2);

        btnVerMontoCuentaAhorro.setText("Ver Monto Actual");
        btnVerMontoCuentaAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMontoCuentaAhorroActionPerformed(evt);
            }
        });

        btnDepositarCuentaAhorro.setText("Depositar");
        btnDepositarCuentaAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarCuentaAhorroActionPerformed(evt);
            }
        });

        btnInvertir.setText("Aceptar");
        btnInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvertirActionPerformed(evt);
            }
        });

        txtMontoActualCuentaAhorro.setEnabled(false);

        jLabel5.setText("Monto Actual");

        lblAccion1.setText("Invertir");

        jLabel6.setText("Depositar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(lblAccion1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtInvertirAhorro)
                    .addComponent(txtMontoActualCuentaAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txtDepositoAhorro))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDepositarCuentaAhorro)
                    .addComponent(btnVerMontoCuentaAhorro)
                    .addComponent(btnInvertir))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMontoActualCuentaAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVerMontoCuentaAhorro))
                    .addComponent(jLabel5))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDepositoAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepositarCuentaAhorro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInvertirAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccion1)
                    .addComponent(btnInvertir))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuenta de Ahorro", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Cuenta de Ahorro");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerMontoCuentaAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMontoCuentaAhorroActionPerformed
        // TODO add your handling code here:
        refrescarMontoCuentaAhorro();
    }//GEN-LAST:event_btnVerMontoCuentaAhorroActionPerformed

    private void btnVerMontoTarjetaCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMontoTarjetaCreditoActionPerformed
        // TODO add your handling code here:
        refrescarMontoCredito();
    }//GEN-LAST:event_btnVerMontoTarjetaCreditoActionPerformed

    private void btnVerMontoTarjetaDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMontoTarjetaDebitoActionPerformed
        // TODO add your handling code here:
        refrescarMontoCuentaDebito();
    }//GEN-LAST:event_btnVerMontoTarjetaDebitoActionPerformed

    private void btnDepositarDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarDebitoActionPerformed
        // TODO add your handling code here:
        double monto = Double.parseDouble(this.txtDepositoDebito.getText());
        this.tarjectaDebito.depositar(monto);
        refrescarMontoCuentaDebito();
    }//GEN-LAST:event_btnDepositarDebitoActionPerformed

    private void btnDepositarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarCreditoActionPerformed
        // TODO add your handling code here:
        double monto = Double.parseDouble(this.txtDepositoCredito.getText());
        this.tarjetaCredito.depositar(monto);
        refrescarMontoCredito();
    }//GEN-LAST:event_btnDepositarCreditoActionPerformed

    private void btnDepositarCuentaAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarCuentaAhorroActionPerformed
        // TODO add your handling code here:
        double monto = Double.parseDouble(this.txtDepositoAhorro.getText());
        this.cuentaAhorro.depositar(monto);
        refrescarMontoCuentaAhorro();
    }//GEN-LAST:event_btnDepositarCuentaAhorroActionPerformed

    private void btnRetirarDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarDebitoActionPerformed
        // TODO add your handling code here:
        double monto = Double.parseDouble(this.txtRetirarDebito.getText());
        this.tarjectaDebito.retirar(monto);
       if(this.tarjectaDebito.getMontoActual()<0)
       {
           JOptionPane.showMessageDialog(null, "El valor a retirar debe ser igual o mayor al monto actual");
           this.tarjectaDebito.depositar(monto);
       }
       
        refrescarMontoCuentaDebito();
    }//GEN-LAST:event_btnRetirarDebitoActionPerformed

    private void btnSumaInteresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaInteresesActionPerformed
        // TODO add your handling code here:
        double monto = Double.parseDouble(this.txtSumaInteresesCredito.getText());
        this.tarjetaCredito.sumaInteres(monto);
        refrescarMontoCredito();
    }//GEN-LAST:event_btnSumaInteresesActionPerformed

    private void btnInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvertirActionPerformed
        // TODO add your handling code here:
        double monto = Double.parseDouble(this.txtInvertirAhorro.getText());
        this.cuentaAhorro.invertir(monto);
        refrescarMontoCuentaAhorro();
    }//GEN-LAST:event_btnInvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositarCredito;
    private javax.swing.JButton btnDepositarCuentaAhorro;
    private javax.swing.JButton btnDepositarDebito;
    private javax.swing.JButton btnInvertir;
    private javax.swing.JButton btnRetirarDebito;
    private javax.swing.JButton btnSumaIntereses;
    private javax.swing.JButton btnVerMontoCuentaAhorro;
    private javax.swing.JButton btnVerMontoTarjetaCredito;
    private javax.swing.JButton btnVerMontoTarjetaDebito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAccion1;
    private javax.swing.JLabel lblAccion2;
    private javax.swing.JLabel lblAccion3;
    private javax.swing.JTextField txtDepositoAhorro;
    private javax.swing.JTextField txtDepositoCredito;
    private javax.swing.JTextField txtDepositoDebito;
    private javax.swing.JTextField txtInvertirAhorro;
    private javax.swing.JTextField txtMontoActualCredito;
    private javax.swing.JTextField txtMontoActualCuentaAhorro;
    private javax.swing.JTextField txtMontoActualDebito;
    private javax.swing.JTextField txtRetirarDebito;
    private javax.swing.JTextField txtSumaInteresesCredito;
    // End of variables declaration//GEN-END:variables
}
